### ISSUE TITLE
p tag bug?(solved)

### ISSUE THREAD

**Issue by washare** [Skrol29/tinybutstrong#27]
[ErrorSample.zip](https://github.com/Skrol29/tinybutstrong/files/9426739/ErrorSample.zip)
I found a strange thing about p tag on use [var.xxx;htmlconv=no].

after replace `<p>[var.hello;htmlconv=no;noerr]</p> `  
p tag appear in error position
`<p></p> `
`<li>hello</li>`
 ` <p></p> `       

if I remove htmlconv=no
it will be correct

if change `<p>to <div>`  ,it will be correct,too.

**Comment by roxblnfk** [comment]
How did you test it?

If you did it in the chrome debug panel:
![img](https://user-images.githubusercontent.com/4152481/186727805-342c9f81-004d-452b-a57e-30c634c2df2c.png)
then there is no bug. Chrome compiles source code to that representation because the `li` tag can't be wrapped by `p` tag.

You should watch the source code.

**Comment by washare** [comment]
I got it~thank you help。
